apiVersion: v2
name: borgserver
version: ${CHART_VERSION}
appVersion: ${BORG_VERSION}
description: Chart for a BorgBackup Server
keywords:
- backup
- borgbackup
- ssh
home: https://github.com/dzervas/docker-borgserver
sources:
- https://github.com/dzervas/docker-borgserver
- https://github.com/lib42/docker-borgserver
- https://borgbackup.readthedocs.io/en/stable
maintainers:
- name: Dimitris Zervas
  email: dzervas@dzervas.gr
- name: nold
  email: nold@gnu.one
