---

apiVersion: v1
kind: ConfigMap
metadata:
  name: authorized-keys
  labels:
    app: borgserver
data:
  authorized-keys: |-
{{- range $client := $.Values.clients }}
    command="borg serve \
    {{- range $path := $client.restrictToPaths -}}
      --restrict-to-path {{ $path }} \
    {{- end -}}
    {{- if $client.appendOnly -}}
      --append-only \
    {{- end -}}
    {{- if $client.storageQuota -}}
      --storage-quota {{ $client.storageQuota }} \
    {{- end }} {{ $.Values.borg.additional_args }}",restrict {{ $client.type }} {{ $client.key }} {{ $client.name }}
{{- end }}
