---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: "{{ .Chart.Name }}"
  ports:
  - name: borg
    port: {{ .Values.service.port | default 2222 }}
    protocol: TCP
