---

name: Build
on:
  schedule:
    - cron: '01 10 * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # TODO: Add support for more platforms
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current version
        id: current_version
        run: |
          docker pull ${{ github.repository }}:latest || true && \
          echo "VERSION=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ github.repository }}:latest | cut -d: -f2)" >> $GITHUB_OUTPUT

      - name: Build
        id: build
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: false
          tags: ${{ github.repository }}:latest

      - name: Build
        if: steps.current_version.outputs.VERSION != steps.build.outputs.digest
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: false
          tags: ${{ github.repository }}:latest
